
service: show-stoppers-lambda


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1


functions:

  getNowAiringTv:
    handler: services/tv/get/handler.getNowAiringTv
    events:
      - http:
          path: tv/now
          method: get
          cors: true

  getTvShowDetails:
    handler: services/tv/get/handler.getShowDetails
    events:
      - http:
          path: tv/{showid}
          method: get
          cors: true

  getTvShowSearch:
    handler: services/tv/get/handler.getShowSearch
    events:
      - http:
          path: tv/search/{query}
          method: get
          cors: true

  getDiscoverTvFilter:
    handler: services/tv/get/handler.getDiscoverTv
    events:
      - http:
          path: tv/filter
          method: get
          cors: true

  getSimilarTvShows:
    handler: services/tv/get/handler.getSimilarShows
    events:
      - http:
          path: tv/similar/{showId}
          method: get
          cors: true


plugins:
  - serverless-offline