
service: show-stoppers-lambda


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1


functions:

  getNowAiringTv:
    handler: services/tv/get/handler.getNowAiringTv
    events:
      - http:
          path: tv/now
          method: get
          cors: true


plugins:
  - serverless-offline